#!/usr/bin/env python3
"""
Generate documentation/examples.md from the current Viva examples.

This is a standalone documentation generation script. It is intentionally
separated from the test suite so that `tests/test_examples.py` remains
purely a test file (no knowledge of documentation file layout or side effects).

Usage:
    python scripts/generate_examples_md.py

The script will overwrite documentation/examples.md with freshly generated
content based on running generateFlowEngine() + .drawFlows() against the examples.
The intro of the generated document now also documents the richer FlowEngine API
(.params, .param_distribs, .getFlows, etc.).
"""

import sys
from collections import defaultdict
from pathlib import Path

# Make sure we can import the viva package
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from viva import generateFlowEngine


def main() -> None:
    examples_dir = Path("examples")
    output_path = Path("documentation/examples.md")

    # Define the examples and the simulation parameters used for documentation.
    # These should be kept in sync with the spirit of test_generateFlowEngine_all_examples
    # but the test file itself stays unaware of this script.
    example_cases = [
        {"name": "example_seminal.viva", "start": 2025, "horizon": 30, "seed": 42},
        {"name": "retirement.viva", "start": 2025, "horizon": 50, "seed": 42},
        {"name": "family_education.viva", "start": 2025, "horizon": 45, "seed": 42},
        {"name": "small_business.viva", "start": 2025, "horizon": 30, "seed": 42},
        {"name": "full_syntax.viva", "start": 2025, "horizon": 20, "seed": 42},
    ]

    lines: list[str] = []

    lines.append("# Viva Examples and Simulated Flows\n")
    lines.append(
        "> This document is generated by `scripts/generate_examples_md.py`.\n\n"
    )
    lines.append(
        "All flows below were produced using `generateFlowEngine(...)`.\n\n"
        "**Simple one-shot usage:**\n\n"
        "```python\n"
        "engine = generateFlowEngine(source, start_year=..., horizon_years=...)\n"
        "flows = engine.drawFlows(seed=...)\n"
        "```\n\n"
        "**For controlled sampling or statistics (recommended):**\n\n"
        "```python\n"
        "engine = generateFlowEngine(...)\n"
        "engine.params              # declared random variables\n"
        "distribs = engine.param_distribs\n"
        "flows = engine.getFlows(**realizations)   # or engine.getFlows(dict)\n"
        "```\n\n"
        "See the main README for the full `FlowEngine` API.\n"
        "Dates are January 1 of each year (MVP).\n"
    )

    for case in example_cases:
        name = case["name"]
        src_path = examples_dir / name
        if not src_path.exists():
            print(f"Warning: {src_path} not found, skipping.", file=sys.stderr)
            continue

        source = src_path.read_text(encoding="utf-8").strip()

        engine = generateFlowEngine(
            source,
            start_year=case["start"],
            horizon_years=case["horizon"],
        )
        events = engine.drawFlows(seed=case["seed"])

        by_name: dict[str, list[tuple[int, float]]] = defaultdict(list)
        for e in events:
            by_name[e["name"]].append((e["date"].year, e["amount"]))

        lines.append(f"\n## {name}\n")
        lines.append("### Source\n")
        lines.append("```viva\n")
        lines.append(source + "\n")
        lines.append("```\n")

        lines.append(f"\n### Simulated Flows ({len(events)} events)\n")
        lines.append(
            f"> Generated with: `generateFlowEngine(..., start_year={case['start']}, "
            f"horizon_years={case['horizon']}).drawFlows(seed={case['seed']})`\n\n"
        )

        if not events:
            lines.append("_(No events produced in this horizon.)_\n")
            continue

        # Summary table
        lines.append("| Name | Years | Events | Sample Amounts |\n")
        lines.append("|------|-------|--------|----------------|\n")

        for fname in sorted(by_name.keys()):
            items = sorted(by_name[fname])
            years = [y for y, _ in items]
            sample_amounts = ", ".join(f"{amt:,.0f}" for _, amt in items[:5])
            yr_str = (
                f"{min(years)}–{max(years)}" if len(set(years)) > 1 else str(years[0])
            )
            lines.append(f"| {fname} | {yr_str} | {len(items)} | {sample_amounts} |\n")

        lines.append("\n<details>\n")
        lines.append("<summary>Full event list (first 60 shown)</summary>\n\n")
        lines.append("| Date | Name | Amount |\n")
        lines.append("|------|------|--------|\n")

        for e in events[:60]:
            lines.append(
                f"| {e['date'].isoformat()} | {e['name']} | {e['amount']:,.0f} |\n"
            )

        if len(events) > 60:
            lines.append(f"| ... | ({len(events) - 60} more events) | ... |\n")

        lines.append("\n</details>\n")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("".join(lines), encoding="utf-8")

    print(f"Generated {output_path} ({output_path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
